import enum
from datetime import date, datetime
from sqlalchemy import Date, DateTime, Enum, ForeignKey, Integer, Numeric, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base
class ProjectType(str, enum.Enum):
    FAB="Semiconductor Fab"; OSAT="OSAT"; ATMP="ATMP"; PACKAGING="Semiconductor Packaging"; TESTING="Semiconductor Testing"; COMPOUND="Compound Semiconductor"; DISPLAY="Display"; MATERIALS="Semiconductor Materials"; EQUIPMENT="Semiconductor Equipment"; RND="Semiconductor R&D"; DESIGN="Semiconductor Design"; OTHER="Other Semiconductor Infrastructure"
class ProjectStatus(str, enum.Enum):
    ANNOUNCED="ANNOUNCED"; PROPOSED="PROPOSED"; APPLICATION="APPLICATION"; APPROVED="APPROVED"; LAND_ACQUIRED="LAND_ACQUIRED"; CONSTRUCTION_STARTED="CONSTRUCTION_STARTED"; UNDER_CONSTRUCTION="UNDER_CONSTRUCTION"; EQUIPMENT_INSTALLATION="EQUIPMENT_INSTALLATION"; TRIAL_PRODUCTION="TRIAL_PRODUCTION"; OPERATIONAL="OPERATIONAL"; EXPANSION="EXPANSION"; DELAYED="DELAYED"; ON_HOLD="ON_HOLD"; CANCELLED="CANCELLED"; COMPLETED="COMPLETED"
class PublicationStatus(str, enum.Enum): DRAFT="DRAFT"; PUBLISHED="PUBLISHED"; ARCHIVED="ARCHIVED"
class Confidence(str, enum.Enum): HIGH="HIGH"; MEDIUM="MEDIUM"; LOW="LOW"
class SourceType(str, enum.Enum): PIB="PIB"; MEITY="MeitY"; ISM="ISM"; CENTRAL="Central Government"; STATE="State Government"; PRESS="Company Press Release"; ANNUAL="Company Annual Report"; INVESTOR="Company Investor Presentation"; EXCHANGE="Stock Exchange Filing"; REGULATORY="Regulatory Filing"; WEBSITE="Company Website"; NEWS="Credible News"; OTHER="Other"
class MilestoneState(str, enum.Enum): NOT_STARTED="NOT_STARTED"; IN_PROGRESS="IN_PROGRESS"; COMPLETE="COMPLETE"; UNKNOWN="UNKNOWN"
class Company(Base):
    __tablename__="companies"
    id: Mapped[int]=mapped_column(primary_key=True); name: Mapped[str]=mapped_column(String(255), unique=True); slug: Mapped[str]=mapped_column(String(255), unique=True)
    description: Mapped[str|None]=mapped_column(Text); website: Mapped[str|None]=mapped_column(String(500)); country: Mapped[str|None]=mapped_column(String(100)); headquarters: Mapped[str|None]=mapped_column(String(255)); company_type: Mapped[str|None]=mapped_column(String(100)); ticker: Mapped[str|None]=mapped_column(String(50)); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow); updated_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    projects: Mapped[list["Project"]]=relationship(back_populates="company")
class Location(Base):
    __tablename__="locations"; id: Mapped[int]=mapped_column(primary_key=True); state: Mapped[str]=mapped_column(String(100), index=True); city: Mapped[str|None]=mapped_column(String(100)); district: Mapped[str|None]=mapped_column(String(100)); latitude: Mapped[float|None]; longitude: Mapped[float|None]
    projects: Mapped[list["Project"]]=relationship(back_populates="location")
class Project(Base):
    __tablename__="projects"; id: Mapped[int]=mapped_column(primary_key=True); slug: Mapped[str]=mapped_column(String(255), unique=True, index=True); project_name: Mapped[str]=mapped_column(String(255), index=True); company_id: Mapped[int]=mapped_column(ForeignKey("companies.id")); location_id: Mapped[int]=mapped_column(ForeignKey("locations.id")); project_type: Mapped[ProjectType]=mapped_column(Enum(ProjectType)); status: Mapped[ProjectStatus]=mapped_column(Enum(ProjectStatus)); publication_status: Mapped[PublicationStatus]=mapped_column(Enum(PublicationStatus), default=PublicationStatus.DRAFT); confidence: Mapped[Confidence]=mapped_column(Enum(Confidence), default=Confidence.MEDIUM)
    facility_type: Mapped[str|None]=mapped_column(String(255)); technology: Mapped[str|None]=mapped_column(Text); location_description: Mapped[str|None]=mapped_column(Text); investment_inr: Mapped[float|None]=mapped_column(Numeric(18,2)); investment_usd: Mapped[float|None]=mapped_column(Numeric(18,2)); approved_investment_inr: Mapped[float|None]=mapped_column(Numeric(18,2)); capacity: Mapped[float|None]=mapped_column(Numeric(18,2)); capacity_unit: Mapped[str|None]=mapped_column(String(100)); capacity_description: Mapped[str|None]=mapped_column(Text); expected_production_date: Mapped[date|None]=mapped_column(Date); actual_construction_start_date: Mapped[date|None]=mapped_column(Date); actual_production_start_date: Mapped[date|None]=mapped_column(Date); employment_estimate: Mapped[int|None]; government_support: Mapped[str|None]=mapped_column(Text); partners: Mapped[str|None]=mapped_column(Text); announcement_date: Mapped[date|None]=mapped_column(Date); approval_date: Mapped[date|None]=mapped_column(Date); last_verified_at: Mapped[date|None]=mapped_column(Date); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow); updated_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    company: Mapped[Company]=relationship(back_populates="projects"); location: Mapped[Location]=relationship(back_populates="projects"); sources: Mapped[list["Source"]]=relationship(back_populates="project", cascade="all, delete-orphan"); milestones: Mapped[list["Milestone"]]=relationship(back_populates="project", cascade="all, delete-orphan"); history: Mapped[list["ProjectHistory"]]=relationship(back_populates="project", cascade="all, delete-orphan")
class Source(Base):
    __tablename__="sources"; id: Mapped[int]=mapped_column(primary_key=True); project_id: Mapped[int]=mapped_column(ForeignKey("projects.id")); source_type: Mapped[SourceType]=mapped_column(Enum(SourceType)); publisher: Mapped[str]=mapped_column(String(255)); title: Mapped[str]=mapped_column(String(500)); url: Mapped[str]=mapped_column(String(1000)); publication_date: Mapped[date|None]=mapped_column(Date); accessed_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow); source_text: Mapped[str|None]=mapped_column(Text); reliability: Mapped[Confidence]=mapped_column(Enum(Confidence), default=Confidence.MEDIUM); notes: Mapped[str|None]=mapped_column(Text); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
    project: Mapped[Project]=relationship(back_populates="sources")
class Milestone(Base):
    __tablename__="milestones"; id: Mapped[int]=mapped_column(primary_key=True); project_id: Mapped[int]=mapped_column(ForeignKey("projects.id")); name: Mapped[str]=mapped_column(String(255)); state: Mapped[MilestoneState]=mapped_column(Enum(MilestoneState)); milestone_date: Mapped[date|None]=mapped_column(Date); source_id: Mapped[int|None]=mapped_column(ForeignKey("sources.id")); notes: Mapped[str|None]=mapped_column(Text)
    project: Mapped[Project]=relationship(back_populates="milestones")
class ProjectHistory(Base):
    __tablename__="project_history"; id: Mapped[int]=mapped_column(primary_key=True); project_id: Mapped[int]=mapped_column(ForeignKey("projects.id")); field_name: Mapped[str]=mapped_column(String(100)); old_value: Mapped[str|None]=mapped_column(Text); new_value: Mapped[str|None]=mapped_column(Text); change_date: Mapped[date]=mapped_column(Date, default=date.today); source_id: Mapped[int|None]=mapped_column(ForeignKey("sources.id")); notes: Mapped[str|None]=mapped_column(Text); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
    project: Mapped[Project]=relationship(back_populates="history")
class RawSource(Base):
    __tablename__="raw_sources"; id: Mapped[int]=mapped_column(primary_key=True); source_url: Mapped[str]=mapped_column(String(1000), unique=True); source_type: Mapped[str]=mapped_column(String(100)); publisher: Mapped[str|None]=mapped_column(String(255)); title: Mapped[str|None]=mapped_column(String(500)); content: Mapped[str|None]=mapped_column(Text); content_hash: Mapped[str]=mapped_column(String(64), index=True); processing_status: Mapped[str]=mapped_column(String(30), default="NEW"); retrieved_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
