"""initial schema

Revision ID: 3825f61267a7
Revises: 
Create Date: 2026-09-08 19:40:18.994875
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3825f61267a7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_page', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_email'), ['email'], unique=False)

    op.create_table('scheme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('administering_body', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'announced', 'superseded', name='schemestatus', native_enum=False), nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=False),
    sa.Column('official_url', sa.String(length=1000), nullable=False),
    sa.Column('last_reviewed_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheme', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheme_code'), ['code'], unique=True)

    op.create_table('source_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('publisher', sa.String(length=300), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('retrieved_on', sa.Date(), nullable=False),
    sa.Column('local_path', sa.String(length=1000), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('sector', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_user_id'), ['user_id'], unique=False)

    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=False),
    sa.Column('clause_ref', sa.String(length=200), nullable=False),
    sa.Column('retrieved_on', sa.Date(), nullable=False),
    sa.Column('confidence', sa.Enum('verified_primary_source', 'secondary_source', 'needs_review', name='confidence', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faq_scheme_id'), ['scheme_id'], unique=False)

    op.create_table('scheme_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'code', name='uq_track_scheme_code')
    )
    with op.batch_alter_table('scheme_track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheme_track_scheme_id'), ['scheme_id'], unique=False)

    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.String(length=200), nullable=False),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('approved_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('preparing', 'applied', 'approved', 'in_disbursement', 'closed', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['scheme_track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_track_id'), ['track_id'], unique=False)

    op.create_table('milestone_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('trigger_type', sa.Enum('date', 'event', 'percentage_of_capex', 'production_start', name='triggertype', native_enum=False), nullable=False),
    sa.Column('typical_offset_days', sa.Integer(), nullable=True),
    sa.Column('disbursement_note_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=False),
    sa.Column('clause_ref', sa.String(length=200), nullable=False),
    sa.Column('retrieved_on', sa.Date(), nullable=False),
    sa.Column('confidence', sa.Enum('verified_primary_source', 'secondary_source', 'needs_review', name='confidence', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['scheme_track.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'sequence', name='uq_milestone_track_seq')
    )
    with op.batch_alter_table('milestone_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestone_template_track_id'), ['track_id'], unique=False)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_application_id'), ['application_id'], unique=False)

    op.create_table('document_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('issuing_authority', sa.String(length=300), nullable=False),
    sa.Column('format_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=False),
    sa.Column('clause_ref', sa.String(length=200), nullable=False),
    sa.Column('retrieved_on', sa.Date(), nullable=False),
    sa.Column('confidence', sa.Enum('verified_primary_source', 'secondary_source', 'needs_review', name='confidence', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['milestone_template_id'], ['milestone_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_requirement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_requirement_milestone_template_id'), ['milestone_template_id'], unique=False)

    op.create_table('milestone_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('milestone_template_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=300), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'submitted', 'disbursed', 'blocked', 'na', name='milestonestatus', native_enum=False), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('notes_md', sa.Text(), nullable=False),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_template_id'], ['milestone_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestone_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestone_instance_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestone_instance_milestone_template_id'), ['milestone_template_id'], unique=False)

    op.create_table('document_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_instance_id', sa.Integer(), nullable=False),
    sa.Column('document_requirement_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('missing', 'drafting', 'ready', 'submitted', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_requirement_id'], ['document_requirement.id'], ),
    sa.ForeignKeyConstraint(['milestone_instance_id'], ['milestone_instance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_instance_document_requirement_id'), ['document_requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_instance_milestone_instance_id'), ['milestone_instance_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_instance_milestone_instance_id'))
        batch_op.drop_index(batch_op.f('ix_document_instance_document_requirement_id'))

    op.drop_table('document_instance')
    with op.batch_alter_table('milestone_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestone_instance_milestone_template_id'))
        batch_op.drop_index(batch_op.f('ix_milestone_instance_application_id'))

    op.drop_table('milestone_instance')
    with op.batch_alter_table('document_requirement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_requirement_milestone_template_id'))

    op.drop_table('document_requirement')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_application_id'))

    op.drop_table('activity_log')
    with op.batch_alter_table('milestone_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestone_template_track_id'))

    op.drop_table('milestone_template')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_track_id'))
        batch_op.drop_index(batch_op.f('ix_application_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_application_company_id'))

    op.drop_table('application')
    with op.batch_alter_table('scheme_track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheme_track_scheme_id'))

    op.drop_table('scheme_track')
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faq_scheme_id'))

    op.drop_table('faq')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_user_id'))

    op.drop_table('company')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('source_document')
    with op.batch_alter_table('scheme', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheme_code'))

    op.drop_table('scheme')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_email'))

    op.drop_table('lead')
    # ### end Alembic commands ###
